included:
    - GitHubClient-Sample
excluded:
    - Pods
disabled_rules:
    - file_length
    - trailing_comma
    - trailing_whitespace
    - vertical_whitespace
    - function_body_length
    - line_length
    - unused_closure_parameter
identifier_name:
    min_length: 1
    allowed_symbols: "_" 
    max_length:  50
type_name:
    allowed_symbols: "_"
    max_length:  50
